<a href="https://colab.research.google.com/github/UttaraKet1607/Covid19-Detection-Using-CNN/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#import tensorflow
import tensorflow as tf
print(tf.__version__)

2.6.0


In [4]:
#create tensors with tf.constant()
scalar = tf.constant(7) #ctrl+shift+space for more info
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
#check number of dimensions of tensor
scalar.ndim

0

In [6]:
#create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [7]:
#check dimension of our vector
vector.ndim

1

In [9]:
#create a matrix (more than one dimension)
matrix = tf.constant([[10,7],
                       [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [10]:
#check dimension of our matrix
matrix.ndim

2

In [11]:
#create another matrix
another_matrix = tf.constant([[10. ,7. ],
                              [3. ,2. ],
                              [8. ,9. ]], dtype = tf.float16) #specify data type with dtype  
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [13]:
#check dimension of another_matrix
another_matrix.ndim

2

In [15]:
#create a tensor
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [17]:
#check dimension of tensor
tensor.ndim

3

Based on things discussed so far:

- Scalar: a single number
- Vector: a number with direction (eg. wind speed and direction)
- Matrix: a 2-dimensional array of numbers
- Tensor: an n-dimensional array of numbers (where n can be any number, a 0 dimensional tensor is scalar, a 1-dimensional tensor is a vector) 